/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import SYSTEM.Partitions;
import SYSTEM.SystemManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author Fanny Brenes
 */
public class SecondWindow extends javax.swing.JFrame {
   private Partitions partition;
   
   public Partitions getPartition() {
        return partition;
    }
    /**
     * Creates new form SecondWindow
     */
    public SecondWindow() {
        initComponents();
        DefaultMutableTreeNode root=new DefaultMutableTreeNode("Particiones");
        
        int x=SystemManager.getInstance().getPartition().size();
        for(int i=0;i<x;i++){
          int w=SystemManager.getInstance().getTree(i).nodecounter();
         
          DefaultMutableTreeNode selectednode=new DefaultMutableTreeNode(SystemManager.getInstance().getPartition(i).getRoot());
          
       
          if(w>1){
          for(int d=0;d<w;d++){
          
          DefaultMutableTreeNode son=new DefaultMutableTreeNode(SystemManager.getInstance().getTree(i).Gettreenode(d).getFile().getName());
           selectednode.add(son);
          }
          }
          

          root.add(selectednode);
        }
        DefaultTreeModel modeloarbol=new DefaultTreeModel (root);
        this.jTree1.setModel(modeloarbol);
        
          
     
          
          DefaultTreeModel model=(DefaultTreeModel)jTree1.getModel();
          model.reload();
     }
    
        
        
      
        
    
       
       
    
     public void refresh(){
        int t=SystemManager.getInstance().getPartition().size();
        
        javax.swing.JButton jButton1[]=new  javax.swing.JButton[t];
        int e=0;
        
     for(int i=0;i<t;i++){
   

        jButton1[i] =new javax.swing.JButton();
        jButton1[i].setText(Integer.toString(i));
        
        
        
        getContentPane().add(jButton1[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(30+e, 40, -1, -1));
        e=e+40;
        
     }
    }
    /**        
        
        getContentPane().add(jButton1[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(30+e, 40, -1, -1));
        e=e+40;
        
     }
    }
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        namera = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Disco duro");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jButton1.setText("Crear particion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Graficar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar particion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Añadir archivo a particion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(namera, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton5))))
                .addContainerGap(327, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    PartitionCreation usuario = new PartitionCreation();
        usuario.setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try{ int e= SystemManager.getInstance().getPartition().size();
        int x=SystemManager.getInstance().getPartition().size();
        for(int i=0;i<x;i++){
        namera.addItem(SystemManager.getInstance().getPartition(i).getRoot());
        }

        
            
          for(int i=0;i<e;i++){
          DefaultMutableTreeNode selectednode=(DefaultMutableTreeNode)jTree1.getSelectionPath().getLastPathComponent();
          DefaultMutableTreeNode newnode=new DefaultMutableTreeNode (SystemManager.getInstance().getPartition(i).getRoot());
          selectednode.add(newnode);
     
          }
          DefaultTreeModel model=(DefaultTreeModel)jTree1.getModel();
          model.reload();}
    catch(Exception e){
    JOptionPane.showMessageDialog(null,"Seleccionar disco duro");
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    DefaultPieDataset dtac= new DefaultPieDataset();
    int x= SystemManager.getInstance().getPartition().size();
    for (int i=0;i<x;i++){
     dtac.setValue(SystemManager.getInstance().getPartition(i).getRoot()+SystemManager.getInstance().getPartition(i).getSize(), SystemManager.getInstance().getPartition(i).getSize());
    }
    dtac.setValue("Espacio libre", SystemManager.getInstance().getHDD(0).getFreespace()+SystemManager.getInstance().getHDD(0).getSize());
    JFreeChart ch= ChartFactory.createPieChart3D("Almacenamiento", dtac, true, true, false);
    ChartPanel cp= new ChartPanel(ch);
    add(cp);
    cp.setBounds(400, 40, 500, 500);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{int x=SystemManager.getInstance().getPartition().size();
       for(int i=0;i<x;i++){
       if(SystemManager.getInstance().getPartition(i).getRoot()==namera.getSelectedItem()){
       SystemManager.getInstance().removePartition(SystemManager.getInstance().getPartition(i));
       
       }
       
       }
       
       DefaultTreeModel model=(DefaultTreeModel)jTree1.getModel();
       
       model.reload();
       }
       catch( Exception e){
       JOptionPane.showMessageDialog(null,"Eliminado correctamente");
       }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    FileCreation usuario = new FileCreation();
        usuario.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecondWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JComboBox<String> namera;
    // End of variables declaration//GEN-END:variables
}
