/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Collections.Validation;
import SYSTEM.FileSystem;
import SYSTEM.HDD;
import SYSTEM.Partitions;
import SYSTEM.SystemManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Fanny Brenes
 */
public class Ventanainicial extends javax.swing.JFrame {
   private Partitions partition;
   private HDD hdd;

    public FileSystem getFile() {
        return file;
    }
   private FileSystem file;
   
   public Partitions getPartition() {
        return partition;
    }
   public HDD getHDD() {
        return hdd;
    }
    /**
     * Creates new form Ventanainicial
     */
    public Ventanainicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsize = new javax.swing.JTextField();
        txtnumber = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsizeActionPerformed(evt);
            }
        });
        getContentPane().add(txtsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 60, -1));

        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 60, -1));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 60, -1));

        jLabel1.setText("Tamaño del disco duro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 160, -1));

        jLabel2.setText("Cantidad de particiones iniciales");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 190, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        jLabel4.setText("Correo del usuario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, -1));

        jButton1.setText("Avanzar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsizeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Validation sec=new Validation();
    
    boolean number=sec.Validate(txtnumber.getText());
    boolean size=sec.Validate(txtsize.getText());
    if (number!=false&&size!=false){
        int w=0;
        int e=Integer.parseInt(txtsize.getText());
        int x=Integer.parseInt(txtnumber.getText());
        float s=(float) e/x/x;
        float su=(float) e/x;
        float u=e-su;
        SystemManager.getInstance().getHDD().clear();
        this.hdd=new HDD();
        this.hdd.setSize(e);
        this.hdd.setFreespace(u);
        this.hdd.setSpaceused(su);
        SystemManager.getInstance().addHDD(hdd);
       
        
        for(int i=0;i<x;i++){
        this.partition= new Partitions();
        this.file=new FileSystem();
        this.file.setName("null");
        this.file.setSize(0);
        String t=Integer.toString(w);
        this.partition.setRoot(t+".NTFS");
        this.partition.setQuantity(x);
        this.partition.setSize(s);
        this.partition.setFile(file);
        SystemManager.getInstance().addPartition(partition);
        
         
        w=w+1;
        }
       
        SecondWindow usuario = new SecondWindow();
        usuario.setVisible(true);
        this.setVisible(false);
    }
    else{
     JOptionPane.showMessageDialog(null,"Error no se puede avanzar");
    }
    
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanainicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtsize;
    // End of variables declaration//GEN-END:variables

}